services:
  synapse:
    container_name: synapse
    build:
      context: ../../
      dockerfile: DockerfileLocal
    image: synapse:latest
    volumes:
      - ../..:/synapse
    ports:
      - "50080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"